MsBadger/Shop

package.json
server/db/index.js
server/db/models/index.js
server/db/models/spaceship.js

take a look at this model we've created and let us know if you LOVE IT
---

add model for spaceship

---

server/seed.js

create seed file with spaceships only (LOVE IT)

---

package.json
server/db/models/spaceship.js
server/seed.js

Database seeded successfully

---

package-lock.json
server/api/index.js
server/api/products.js

Backend get routes

---

client/app.js
client/components/Main.js
client/components/ProductsList.js
package-lock.json
package.json

Include Main.js and ProductsList.js

---

client/store/index.js
client/store/spaceships.js

combined reducer add spaceship and spaceships

---

client/components/Main.js
client/components/ProductsList.js
client/store/index.js
client/store/spaceships.js

All products rendering

---

package-lock.json
package.json
server/db/models/user.js
server/seed.js

seed users

---

client/components/ProductsList.js
public/style.css

All Products styled

---

server/api/products.js

Product backend post put

---

client/components/AddSpaceship.js
client/components/Main.js
client/components/index.js
client/components/navbar.js
client/store/spaceships.js
server/api/products.js

Addproduct

---

client/components/ProductPage.js
client/components/navbar.js
public/index.html
public/style.css

styling for singles

---

client/components/UpdateSpaceship.js
client/store/spaceships.js
server/api/products.js

Newest form

---

server/db/models/index.js
server/db/models/lineItems.js
server/db/models/order.js

Order models and associations including LineItems

---

client/components/Cart.js
server/api/carts.js
server/api/index.js
server/api/users.js

DO YOU LOVE IT?
DO U?
DO YOU>
????
---

Express cart

---

client/components/ProductPage.js
server/api/index.js
server/api/users.js

-Add to cart button
- Backend route to post

Add button

---

client/components/AddSpaceship.js
client/components/UpdateSpaceship.js
server/api/products.js

Image URL validations for update and add product forms

---

server/seed.js

Added info to seed file:
1. Orders added
2. Line Items added
Remember 101 is omri --> admin

Expanded seed file

---

client/components/Cart.js
client/store/cart.js

Cart component2

---

server/db/models/index.js
server/db/models/review.js
server/seed.js

review model and seed file for review model closes #72

---

client/components/Cart.js
client/components/navbar.js
client/store/cart.js
public/style.css
server/api/users.js
server/seed.js

cart in agoo shape

---

client/components/AddSpaceship.js
client/components/Cart.js
client/components/navbar.js
client/store/cart.js
client/store/spaceships.js
public/style.css
server/api/users.js
server/seed.js

1✅ **REMOVE ITEM fixed  functionality**: 
it was a matter of ajax route, we should've sent userId as an argument :)
now user can remove an item and then page rerenders automatically ;
2✅ **STYLE HEADER rearrangement:** 
cart-icon and menu  positioned properly;
3 ✴️ **REMOVE CART **: 
now user can remove the cart and then we send ajax request to get the new cart,
but the **page doesn't reload properly** and an empty page is shown instead , 
if you press renew icon in chrome bar 
only then it rerenders with a new empty cart as it should do.
OPTIONS: 
we can simly redirect the user to the home page after the cart was removed, 
or we can keep it how it is and ask Kate/Ashi for advice :)

Cart component3

---

client/components/ProductPage.js
client/store/index.js
client/store/review.js
client/store/spaceship.js
server/api/products.js

…ime the productpage mounts. The productpage then renders snippets of each of the fetched reviews along with the rating - the author/user name is not displaying because the associated user is not eager-loaded at this time.
---

Basic review functionality on product page

---

client/components/Cart.js
client/components/Home.js
client/components/Main.js
client/components/ProductPage.js
client/components/ProductsList.js
client/store/cart.js
server/api/users.js

Add products2

---

client/components/Cart.js
client/components/Home.js

Guest user working

---

.vscode/settings.json
client/components/Cart.js
client/components/Main.js
client/components/ProductPage.js
public/style.css
server/api/users.js

Subtotal, Order history in progress

---

client/components/AddSpaceship.js
package-lock.json
package.json

Redirect works properly after adding a new product

---

.gitignore
client/components/Cart.js
client/components/Checkout.js
client/components/Main.js
client/components/index.js
constants/server.js
constants/stripe.js
package-lock.json
package.json
server/api/index.js
server/api/payments.js
server/index.js

the stripe is implemented but
- we have amounts hard coded
---

Stripe checkout

---

client/components/Checkout.js
client/components/Main.js
client/components/index.js
constants/server.js
constants/stripe.js
server/api/index.js
server/api/payments.js
server/index.js

re-did stripe stuff

---

client/components/Cart.js
client/store/cart.js
server/api/users.js

quantitites dropdown in cart now defaults to actual item amounts

---

client/components/Home.js
client/components/navbar.js
public/style.css

styling and stuff
